// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WilmerCastillo_AP1_P2.DAL;

#nullable disable

namespace WilmerCastillo_AP1_P2.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241119002830_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.Combos", b =>
                {
                    b.Property<int>("CombosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CombosId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("Vendido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CombosId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.CombosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CombosId")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<int>("ProductosId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("CombosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("CombosDetalle");
                });

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.Productos", b =>
                {
                    b.Property<int>("ProductosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductosId"));

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiscoDuro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<string>("MemoriaGrafica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemoriaRam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("Procesador")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductosId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductosId = 1,
                            Costo = 2500.0,
                            Descripcion = "Combo1",
                            DiscoDuro = "DHCD",
                            Existencia = 10,
                            MemoriaGrafica = "4GB",
                            MemoriaRam = "16Gb",
                            Precio = 3000.0,
                            Procesador = "Ryzen"
                        },
                        new
                        {
                            ProductosId = 2,
                            Costo = 4500.0,
                            Descripcion = "Combo2",
                            DiscoDuro = "DHCD",
                            Existencia = 5,
                            MemoriaGrafica = "8GB",
                            MemoriaRam = "32Gb",
                            Precio = 6000.0,
                            Procesador = "Ryzen7"
                        });
                });

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.CombosDetalle", b =>
                {
                    b.HasOne("WilmerCastillo_AP1_P2.Models.Combos", "Combos")
                        .WithMany("CombosDetalle")
                        .HasForeignKey("CombosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WilmerCastillo_AP1_P2.Models.Productos", "Productos")
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.Combos", b =>
                {
                    b.Navigation("CombosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
