// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WilmerCastillo_AP1_P2.DAL;

#nullable disable

namespace WilmerCastillo_AP1_P2.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.Combo1", b =>
                {
                    b.Property<int>("CombosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CombosId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<bool>("Vendido")
                        .HasColumnType("bit");

                    b.HasKey("CombosId");

                    b.ToTable("Combo1");
                });

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.ComboDetalles", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CombosId")
                        .HasColumnType("int");

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<int>("ProductosId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("CombosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("ComboDetalles");
                });

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.Product", b =>
                {
                    b.Property<int>("ProductosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductosId"));

                    b.Property<double>("Costo")
                        .HasColumnType("float");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.HasKey("ProductosId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ProductosId = 1,
                            Costo = 1000.0,
                            Descripcion = "Disco Duro",
                            Existencia = 20,
                            Precio = 1500.0
                        },
                        new
                        {
                            ProductosId = 2,
                            Costo = 800.0,
                            Descripcion = "Memoria Ram",
                            Existencia = 30,
                            Precio = 2200.0
                        },
                        new
                        {
                            ProductosId = 3,
                            Costo = 3000.0,
                            Descripcion = "Procesador",
                            Existencia = 50,
                            Precio = 3810.0
                        },
                        new
                        {
                            ProductosId = 4,
                            Costo = 1310.0,
                            Descripcion = "Memoria Grafica",
                            Existencia = 40,
                            Precio = 2530.0
                        });
                });

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.ComboDetalles", b =>
                {
                    b.HasOne("WilmerCastillo_AP1_P2.Models.Combo1", "Combos")
                        .WithMany("CombosDetalle")
                        .HasForeignKey("CombosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WilmerCastillo_AP1_P2.Models.Product", "Productos")
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combos");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("WilmerCastillo_AP1_P2.Models.Combo1", b =>
                {
                    b.Navigation("CombosDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
